sample_sheet: "samples.csv"  # Path to the sample sheet
star_index: "genome_index"  # Path to STAR reference genome index folder or URL
star_extra: "--outSAMtype BAM SortedByCoordinate"  # Additional STAR parameters