sample_sheet: "samples.csv" # Path to the sample sheet
refGenomePathOrUrl: "https://ftp.ensembl.org/pub/release-113/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz" #genome fasta
star_extra: "--outSAMtype BAM SortedByCoordinate" # Additional STAR parameters
